import { Shield, Eye, Lock, AlertTriangle, Search, Baby, ShieldAlert, Brain, Users, Scale, BookOpen, ScanEye, MousePointerClick, Flame, Compass, Hexagon, Microscope, Heart, HeartPulse, Gavel, MessageCircle, ShieldCheck, GraduationCap, Vote, Wallet, Bot, Fingerprint, ImageOff, HeartHandshake, Landmark, Lightbulb, Handshake, Radar, LifeBuoy, Target, Siren, School, Library, HandHeart, Building2, ScrollText, IdCard, type LucideIcon } from "lucide-react"
import type { Audiencia } from "./audiencias"

export interface TematicaItem {
  id: string
  href: string
  category: string
  title: string
  description: string
  image: string
  imageAlt: string
  icon: LucideIcon
  color: string
  // Requiere ser miembro de la plataforma (Ciudadanía Presente) para acceder
  // — gatea el link en /tematicas, redirigiendo a /ciudadania-presente/modulos.
  // No dice nada sobre si el contenido en sí ya existe.
  locked: boolean
  // La ruta (`href`) todavía no tiene página real construida (404 si se
  // navega). Distinto de `locked`: una temática puede estar `locked` (requiere
  // membresía) y tener contenido real, o —como acá— no tener contenido
  // todavía independientemente de la membresía. En el dashboard de la
  // plataforma (`/dashboard/tematicas`) esto se usa para mostrar "Próximamente"
  // en vez de la card navegable normal, y para saltear el ítem del cálculo de
  // desbloqueo secuencial del módulo (no bloquea a los que vienen después).
  sinContenido?: boolean
  // Públicos a los que el contenido, tal como está redactado hoy, le sirve.
  // Ausente = sin clasificar (contenido ambiguo/neutro) — no asumir "todos los
  // públicos" ni mostrar en filtros de público activos. Ver
  // content-management/PROPUESTA-AUDIENCIAS.md para el criterio por temática.
  audiencias?: Audiencia[]
}

export interface TematicaGroup {
  label: string
  accent: string
  items: TematicaItem[]
}

export const groups: TematicaGroup[] = [
  {
    label: "Ciudadanía Digital",
    accent: "#4272BB",
    items: [
      {
        id: "ciudadania-digital",
        href: "/ciudadania-digital",
        category: "Kit de Acción",
        title: "Ciudadanía Digital",
        description: "Protocolo de seguridad, netiqueta y detección de bulos. Un kit interactivo para ejercer tus derechos y responsabilidades en el mundo digital.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Ciudadanía Digital",
        icon: Shield,
        color: "#4272BB",
        locked: false,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "instrumental-y-acceso",
        href: "/tematicas/instrumental-y-acceso",
        category: "Acceso Digital",
        title: "Instrumental y Acceso",
        description: "Primera dimensión del Poliedro: herramientas simples para distinguir si una dificultad digital es de la persona o del diseño, y ganar autonomía real.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Instrumental y Acceso",
        icon: Shield,
        color: "#4272BB",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "cognitivo-intelectual-e-informacional",
        href: "/tematicas/cognitivo-intelectual-e-informacional",
        category: "Verificación de Información",
        title: "Cognitivo-Intelectual e Informacional",
        description: "Segunda dimensión del Poliedro: claves para evaluar la calidad de la información, aplicar la lectura lateral y saber cuánto verificar en cada caso.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Cognitivo-Intelectual e Informacional",
        icon: Microscope,
        color: "#4272BB",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "socio-comunicacional-e-identidad",
        href: "/tematicas/socio-comunicacional-e-identidad",
        category: "Comunicación e Identidad",
        title: "Socio-Comunicacional e Identidad",
        description: "Tercera dimensión del Poliedro: cómo anticipar la audiencia, la persistencia y la circulación de lo que decimos, y aprender a reparar cuando algo sale mal.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Socio-Comunicacional e Identidad",
        icon: MessageCircle,
        color: "#4272BB",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "emocional",
        href: "/tematicas/emocional",
        category: "Regulación Emocional",
        title: "Emocional",
        description: "Cuarta dimensión del Poliedro: cómo las emociones guían nuestras decisiones digitales y cuándo conviene pausar, pedir una segunda mirada o pedir ayuda.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Emocional",
        icon: Heart,
        color: "#4272BB",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "huella-digital",
        href: "/huella-digital",
        category: "Privacidad",
        title: "Huella Digital",
        description: "Auditá tu exposición en internet y gestioná tu identidad digital. Descubrí qué datos tuyos son públicos y cómo recuperar el control.",
        image: "/img/cards/hueDig.jpg",
        imageAlt: "Banner Huella Digital",
        icon: Eye,
        color: "#D5247A",
        locked: true,
        audiencias: ["familias", "docentes"],
      },
      {
        id: "hiperconectividad-digital",
        href: "/hiperconectividad-digital",
        category: "Neurodesarrollo",
        title: "Hiperconectividad Digital",
        description: "Impacto de las pantallas y redes sociales en el cerebro adolescente. Evidencia científica sobre FOMO, cultura del like y salud mental en la era TRIC.",
        image: "/img/cards/hiperDig.jpg",
        imageAlt: "Banner Hiperconectividad Digital",
        icon: Brain,
        color: "#6366F1",
        locked: true,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "salud-y-bienestar-digital",
        href: "/tematicas/salud-y-bienestar-digital",
        category: "Bienestar Digital",
        title: "Salud y Bienestar Digital",
        description: "Quinta dimensión del Poliedro: por qué el bienestar digital no se mide en horas de pantalla, y qué depende de cada persona y qué del entorno.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Salud y Bienestar Digital",
        icon: HeartPulse,
        color: "#059669",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "etico-normativa-y-derechos",
        href: "/tematicas/etico-normativa-y-derechos",
        category: "Ética y Normas",
        title: "Ético-Normativa y Derechos",
        description: "Sexta dimensión del Poliedro: criterios claros para decidir qué está bien, más allá de lo que la tecnología permite hacer.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Ético-Normativa y Derechos",
        icon: Gavel,
        color: "#7C3AED",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "seguridad-privacidad-y-proteccion-digital",
        href: "/tematicas/seguridad-privacidad-y-proteccion-digital",
        category: "Seguridad Digital",
        title: "Seguridad, Privacidad y Protección Digital",
        description: "Séptima dimensión del Poliedro: qué proteger hoy y cómo usar Pausar–Verificar–Decidir frente a la urgencia y la autoridad aparente.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Seguridad, Privacidad y Protección Digital",
        icon: ShieldCheck,
        color: "#0E7490",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "pedagogica-y-creativa",
        href: "/tematicas/pedagogica-y-creativa",
        category: "Aprendizaje y Creatividad",
        title: "Pedagógica y Creativa",
        description: "Octava dimensión del Poliedro: cómo aprender y crear con tecnología sin perder la capacidad de pensar por cuenta propia.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Pedagógica y Creativa",
        icon: GraduationCap,
        color: "#EA580C",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "participacion-y-democracia",
        href: "/tematicas/participacion-y-democracia",
        category: "Participación Ciudadana",
        title: "Participación y Democracia",
        description: "Novena dimensión del Poliedro: la diferencia entre opinar y lograr que una voz incida de verdad en una decisión colectiva.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Participación y Democracia",
        icon: Vote,
        color: "#BE185D",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "economica-productiva-y-de-consumo",
        href: "/tematicas/economica-productiva-y-de-consumo",
        category: "Consumo Digital",
        title: "Económica, Productiva y de Consumo",
        description: "Décima y última dimensión del Poliedro: las condiciones reales detrás de una compra, una suscripción o una herramienta de trabajo automatizada.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía (misma familia del Poliedro).
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Económica, Productiva y de Consumo",
        icon: Wallet,
        color: "#166534",
        locked: false,
        audiencias: ["docentes"],
      },
    ],
  },
  {
    label: "Alfabetización",
    accent: "#0EA5E9",
    items: [
      {
        id: "alfabetizacion-digital",
        href: "/alfabetizacion-digital",
        category: "Habilidades Digitales",
        title: "Alfabetización Digital",
        description: "Competencias esenciales para desenvolverse en el entorno digital: uso de dispositivos, navegación segura, gestión de aplicaciones y comunicación en línea.",
        image: "/weekly-content/2026-W20/amipng.png",
        imageAlt: "Banner Alfabetización Digital",
        icon: BookOpen,
        color: "#0EA5E9",
        locked: false,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "alfabetizacion-mediatica",
        href: "/alfabetizacion-mediatica",
        category: "Información",
        title: "Alfabetización Mediática",
        description: "Herramientas y frameworks para consumir y compartir información con criterio. Aprendé a detectar desinformación y fake news.",
        image: "/img/cards/alfabetizacion/alfMed.jpg",
        imageAlt: "Banner Alfabetización Mediática",
        icon: Search,
        color: "#00D4AA",
        locked: true,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "la-persona-no-es-un-dato",
        href: "/la-persona-no-es-un-dato",
        category: "Datos y privacidad",
        title: "La Persona No Es un Dato",
        description: "Por qué cuidar los datos personales es cuidar a la persona, y qué significa eso en la práctica cotidiana.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner La Persona No Es un Dato",
        icon: IdCard,
        color: "#0EA5E9",
        locked: true,
        sinContenido: false,
      },
    ],
  },
  {
    label: "Seguridad",
    accent: "#F59E0B",
    items: [
      {
        id: "estafas-digitales",
        href: "/estafas-digitales",
        category: "Phishing y Estafas",
        title: "Estafas Digitales",
        description: "Phishing, smishing y vishing: aprendé a detectarlos antes de que sea tarde. Protocolo paso a paso para actuar si sos víctima.",
        image: "/weekly-content/2026-W23/estafapng.png",
        imageAlt: "Banner Estafas Digitales",
        icon: AlertTriangle,
        color: "#F59E0B",
        locked: false,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "ciberdelitos-digitales",
        href: "/ciberdelitos-digitales",
        category: "Delitos Digitales",
        title: "Ciberdelitos y Delitos Facilitados por Tecnología",
        description: "Qué delitos cambian de forma cuando se cometen con tecnología, y cómo reconocerlos y actuar frente a ellos. Próximamente.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía.
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Ciberdelitos y Delitos Facilitados por Tecnología",
        icon: Fingerprint,
        color: "#F59E0B",
        locked: true,
        sinContenido: false,
      },
      {
        id: "ingenieria-social-y-confianza",
        href: "/ingenieria-social-y-confianza",
        category: "Ingeniería Social",
        title: "Ingeniería Social y Confianza",
        description: "Pausar–Verificar–Decidir: cómo reconocer cuándo alguien está explotando tu confianza para que actúes rápido y sin pensar.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Ingeniería Social y Confianza",
        icon: Handshake,
        color: "#F59E0B",
        locked: true,
        sinContenido: false,
      },
      {
        id: "rutinas-exposicion-y-guardania",
        href: "/rutinas-exposicion-y-guardania",
        category: "Hábitos y Exposición",
        title: "Rutinas, Exposición y Guardianía",
        description: "Por qué los mismos hábitos digitales que facilitan la vida también definen cuánto expuesto estás, y qué significa tener un \"guardián\" en un entorno digital.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Rutinas, Exposición y Guardianía",
        icon: Radar,
        color: "#F59E0B",
        locked: true,
        sinContenido: false,
      },
      {
        id: "victimologia-digital",
        href: "/victimologia-digital",
        category: "Victimología",
        title: "Victimología Digital",
        description: "Qué hacer y a dónde recurrir si ya fuiste víctima de un hecho digital, desde la primera reacción hasta la reparación.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Victimología Digital",
        icon: LifeBuoy,
        color: "#F59E0B",
        locked: true,
        sinContenido: false,
      },
      {
        id: "riesgo-y-proteccion-digital",
        href: "/riesgo-y-proteccion-digital",
        category: "Gestión de Riesgo",
        title: "Riesgo y Protección Digital",
        description: "Un marco para pensar en probabilidades, no en certezas: cuándo un riesgo digital amerita actuar y cuándo no.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Riesgo y Protección Digital",
        icon: Target,
        color: "#F59E0B",
        locked: true,
        sinContenido: false,
      },
    ],
  },
  {
    label: "Violencia Digital",
    accent: "#FF6B35",
    items: [
      {
        id: "violencia-digital",
        href: "/violencia-digital",
        category: "Derechos",
        title: "Violencia Digital hacia la Mujer",
        description: "Guía completa sobre ciberbullying, acoso en línea y violencia de género digital. Conocé tus derechos y cómo actuar si sos víctima.",
        image: "/weekly-content/2026-W22/violenciapng.png",
        imageAlt: "Banner Violencia Digital hacia la Mujer",
        icon: Lock,
        color: "#FF6B35",
        locked: false,
        audiencias: ["mujeres", "docentes", "familias"],
      },
      {
        id: "violencia-digital-infancias",
        href: "/violencia-digital-infancias",
        category: "Grooming y Ciberbullying",
        title: "Violencia Digital en Infancias",
        description: "Grooming, ciberbullying y exposición a riesgos: cómo identificar señales de alerta y actuar a tiempo para proteger a niñas, niños y adolescentes.",
        image: "/weekly-content/2026-W25/card7.png",
        imageAlt: "Banner Violencia Digital en Infancias",
        icon: ShieldAlert,
        color: "#EF4444",
        locked: true,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "danos-sinteticos-e-intimidad-digital",
        href: "/danos-sinteticos-e-intimidad-digital",
        category: "Contenido Sintético",
        title: "Infancias, Intimidad y Daños Sintéticos",
        description: "Consentimiento, intimidad y contenido sintético no consentido: un riesgo digital distinto del grooming o el ciberbullying, y cómo responder frente a él. Próximamente.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía.
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Infancias, Intimidad y Daños Sintéticos",
        icon: ImageOff,
        color: "#EF4444",
        locked: true,
        sinContenido: false,
      },
      {
        id: "deteccion-respuesta-y-reparacion",
        href: "/deteccion-respuesta-y-reparacion",
        category: "Protocolo de Respuesta",
        title: "Detección, Respuesta y Reparación",
        description: "Protocolo institucional para actuar frente a un caso de violencia digital ya ocurrido: detectar, interrumpir, responder y reparar.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Detección, Respuesta y Reparación",
        icon: Siren,
        color: "#FF6B35",
        locked: true,
        sinContenido: false,
      },
    ],
  },
  {
    label: "Libres bajo influencia",
    accent: "#9333EA",
    items: [
      {
        id: "subculturas-digitales",
        href: "/tematicas/subculturas-digitales",
        category: "Comunidad digital",
        title: "Subculturas digitales",
        description: "Por qué lo digital funciona más como un territorio que como una herramienta, y cómo se forman ahí dentro comunidades con códigos, lenguaje y normas propias.",
        image: "/img/cards/libres%20bajo%20influencia/subculDig.jpg",
        imageAlt: "Infografía de Subculturas digitales",
        icon: Users,
        color: "#9333EA",
        locked: false,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "algoritmos-perfilado",
        href: "/tematicas/algoritmos-perfilado",
        category: "Datos y algoritmos",
        title: "Algoritmos y perfilado",
        description: "Cómo cada gesto digital deja una señal, cómo esas señales se convierten en un perfil, y qué significa realmente que un sistema \"nos conozca\".",
        image: "/img/cards/libres%20bajo%20influencia/algPerf.jpg",
        imageAlt: "Infografía de Algoritmos y perfilado",
        icon: ScanEye,
        color: "#2563EB",
        locked: true,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "diseno-persuasivo-patrones-oscuros",
        href: "/tematicas/diseno-persuasivo-patrones-oscuros",
        category: "Diseño digital",
        title: "Diseño persuasivo y patrones oscuros",
        description: "Por qué la influencia digital rara vez llega como una orden, y dónde está la línea entre un diseño que ayuda y uno que manipula.",
        image: "/img/cards/libres%20bajo%20influencia/patroOscuros.jpg",
        imageAlt: "Infografía Diseño persuasivo y patrones oscuros",
        icon: MousePointerClick,
        color: "#DB2777",
        locked: true,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "caldos-de-cultivo",
        href: "/tematicas/caldos-de-cultivo",
        category: "Desinformación",
        title: "Caldos de cultivo",
        description: "Cómo se combinan repetición, polarización y viralidad emocional hasta crear un ambiente donde la desinformación se propaga más rápido que la verdad.",
        image: "/img/cards/libres%20bajo%20influencia/caldCult.jpg",
        imageAlt: "Infografía de Caldos de cultivo",
        icon: Flame,
        color: "#EA580C",
        locked: true,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "recuperar-la-agencia",
        href: "/tematicas/recuperar-la-agencia",
        category: "Autonomía",
        title: "Recuperar la agencia",
        description: "Reconocer todo lo anterior no significa negar nuestra capacidad de actuar: significa fortalecerla. Herramientas concretas para decidir con más conciencia.",
        image: "/img/cards/libres%20bajo%20influencia/recupAgencia.jpg",
        imageAlt: "Infografía de Recuperar la agencia",
        icon: Compass,
        color: "#059669",
        locked: true,
        audiencias: ["docentes", "familias", "ninas-ninos-adolescentes"],
      },
      {
        id: "poliedro-ciudadania-digital",
        href: "/tematicas/poliedro-ciudadania-digital",
        category: "Ciudadanía digital",
        title: "Ciudadanía digital: el poliedro",
        description: "La tesis de toda la charla: formar ciudadanía digital, no solamente usuarios. Un poliedro de ocho caras y la respuesta final a la paradoja del título.",
        image: "/img/cards/libres%20bajo%20influencia/poliedro.jpg",
        imageAlt: "Infografía Ciudadanía digital: el poliedro",
        icon: Hexagon,
        color: "#0EA5E9",
        locked: true,
        audiencias: ["docentes"],
      },
    ],
  },
  {
    label: "Inteligencia Artificial",
    accent: "#4F46E5",
    // Criterio editorial: cualquier temática nueva relacionada con IA debería
    // evaluarse para este grupo en vez de crearse suelta en otro.
    items: [
      {
        id: "usar-la-ia-sin-perder-criterio",
        href: "/ia/usar-la-ia-sin-perder-criterio",
        category: "Criterio y Delegación",
        title: "Usar la IA sin perder criterio",
        description: "Primera temática del módulo Inteligencia Artificial: cuándo usar una IA es ampliar tu capacidad y cuándo es delegar un criterio que te corresponde conservar.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía.
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Usar la IA sin perder criterio",
        icon: Bot,
        color: "#4F46E5",
        locked: false,
        audiencias: ["docentes"],
      },
      {
        id: "ia-etica-ciudadania",
        href: "/tematicas/ia-etica-ciudadania",
        category: "IA & Ética",
        title: "IA, Ética y Ciudadanía Digital",
        description: "La integración de la Inteligencia Artificial en el tejido social: economía del conocimiento, humanidad ampliada, AI Act 2024 y justicia digital con perspectiva de género.",
        image: "/img/cards/alfabetizacion/iaEtic.jpg",
        imageAlt: "Banner IA, Ética y Ciudadanía Digital",
        icon: Scale,
        color: "#00A99D",
        locked: true,
        audiencias: ["docentes", "familias"],
      },
      {
        id: "la-universidad-ante-la-ia",
        href: "/ia/la-universidad-ante-la-inteligencia-artificial",
        category: "Integridad Académica",
        title: "La Universidad ante la Inteligencia Artificial",
        description: "Integridad académica, evaluación y criterio docente en un escenario donde el estudiantado ya usa IA todos los días.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner La Universidad ante la Inteligencia Artificial",
        icon: Library,
        color: "#4F46E5",
        locked: true,
        sinContenido: false,
      },
    ],
  },
  {
    label: "Infancia y Crianza",
    accent: "#14B8A6",
    items: [
      {
        id: "cibercrianza",
        href: "/tematicas/cibercrianza",
        category: "Cibercrianza",
        title: "¿Sabés dónde interactúan tus estudiantes?",
        description: "Cibercrianza: datos reales, quiz interactivo y claves para acompañar a tus estudiantes en el entorno digital.",
        image: "/img/cards/infancia%20t%20crianza/cibercri.jpg",
        imageAlt: "Banner Cibercrianza",
        icon: Users,
        color: "#14B8A6",
        locked: false,
        audiencias: ["familias", "docentes"],
      },
      {
        id: "nnya-entorno-digital",
        href: "/nnya-entorno-digital",
        category: "Infancia",
        title: "Niñas, Niños y Adolescentes en el Entorno Digital",
        description: "Cómo interpretan los niños, niñas y adolescentes el mundo digital. Guía práctica de mediación parental para acompañarlos de forma consciente.",
        image: "/img/cards/infancia%20t%20crianza/nnyAEntDig.jpg",
        imageAlt: "Banner NNyA y el Entorno Digital",
        icon: Baby,
        color: "#7C3AED",
        locked: true,
        audiencias: ["familias", "docentes"],
      },
      {
        id: "autonomia-progresiva-familiar",
        href: "/tematicas/autonomia-progresiva-familiar",
        category: "Familia",
        title: "Autonomía Progresiva en Familia",
        description: "Cómo acompañar a cada hijo o hija según su etapa, sin sobreproteger ni desentenderse: un marco de confianza y autonomía progresiva para la crianza digital. Próximamente.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía.
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Autonomía Progresiva en Familia",
        icon: HeartHandshake,
        color: "#14B8A6",
        locked: true,
        sinContenido: false,
      },
      {
        id: "la-escuela-como-espacio-civico",
        href: "/tematicas/la-escuela-como-espacio-civico",
        category: "Educación",
        title: "La Escuela como Espacio Cívico",
        description: "Cómo la escuela puede formar ciudadanía digital más allá de prohibir o permitir pantallas.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner La Escuela como Espacio Cívico",
        icon: School,
        color: "#14B8A6",
        locked: true,
        sinContenido: false,
      },
    ],
  },
  {
    label: "Gobierno y Comunidad Digital",
    accent: "#1D4ED8",
    items: [
      {
        id: "gobiernos-locales-y-administracion-publica",
        href: "/tematicas/gobiernos-locales-y-administracion-publica",
        category: "Gobierno Abierto",
        title: "Gobiernos Locales y Administración Pública",
        description: "Cómo un gobierno local puede incorporar tecnología sin perder cercanía ni rendición de cuentas, y qué significa participación ciudadana digital desde el Estado. Próximamente.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía.
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Gobiernos Locales y Administración Pública",
        icon: Landmark,
        color: "#1D4ED8",
        locked: true,
        sinContenido: false,
      },
      {
        id: "comunidad-y-organizaciones-sociales",
        href: "/tematicas/comunidad-y-organizaciones-sociales",
        category: "Organización Comunitaria",
        title: "Comunidad y Organizaciones Sociales",
        description: "Cómo las organizaciones comunitarias pueden organizarse y actuar con herramientas digitales sin perder su propósito.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Comunidad y Organizaciones Sociales",
        icon: HandHeart,
        color: "#1D4ED8",
        locked: true,
        sinContenido: false,
      },
      {
        id: "empresas-organizaciones-y-plataformas",
        href: "/tematicas/empresas-organizaciones-y-plataformas",
        category: "Responsabilidad de Plataformas",
        title: "Empresas, Organizaciones y Plataformas",
        description: "Qué responsabilidad tienen las plataformas y las empresas en las condiciones digitales que les imponen a sus usuarios y trabajadores.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Empresas, Organizaciones y Plataformas",
        icon: Building2,
        color: "#1D4ED8",
        locked: true,
        sinContenido: false,
      },
      {
        id: "justicia-en-el-territorio-hibrido",
        href: "/tematicas/justicia-en-el-territorio-hibrido",
        category: "Justicia Digital",
        title: "Justicia en el Territorio Híbrido",
        description: "Cómo cambia el acceso a la justicia cuando el delito, la prueba o el daño ocurren en entornos digitales.",
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner Justicia en el Territorio Híbrido",
        icon: ScrollText,
        color: "#1D4ED8",
        locked: true,
        sinContenido: false,
      },
    ],
  },
  {
    label: "IDEAY+",
    accent: "#CA8A04",
    items: [
      {
        id: "ideay-mas",
        href: "/ideay-mas",
        category: "Metodología",
        title: "IDEAY+",
        description: "La metodología de construcción colectiva de posibilidades: cómo pasar de un diagnóstico a una idea, y de una idea a una acción concreta. Próximamente.",
        // Reutiliza el banner de Ciudadanía Digital a falta de arte propio todavía.
        image: "/img/cards/ciudDig.jpg",
        imageAlt: "Banner IDEAY+",
        icon: Lightbulb,
        color: "#CA8A04",
        locked: true,
        sinContenido: false,
      },
    ],
  },
]
